### ISSUE TITLE
Re-add iPhone-like diagram art

### ISSUE THREAD

**Issue by ybakos** [SwiftEducation/presentations#2]
While we can't use photos of real hardware in here and remain compliant with our CC license, we should be able to use original art. A colleague created some very elegant device art that resembles an Apple device but is indeed original art. Need to check with Apple to make sure that using the art won't put us into any legal situation.

This needs to be re-added to existing Keynotes, existing Keynote master slides, and the Keynote template.

**Comment by zerausolrac** [comment]
@ybakos  I will clone all presentations! Thanks!
